# appveyor.yml

clone_folder: c:\gopath\src\github.com\spacemeshos\go-spacemesh\

environment:
  GOPATH: c:\gopath

stack: go 1.15

before_build:
  - choco install make

build_script:
  - cmd: set PATH=%PATH%;C:\Users\appveyor\protoc-3.6.1\bin;C:\gopath\bin;
  - make all
