# sample spacemesh config file

# Main Config
data-folder = "~/.spacemesh"

# Node Config
security-param = 20
fast-sync = true
tcp-port = 7512
node-id = ""
dial-timeout = "1m"
conn-keepalive = "48h"

# Node Swarm Config
swarm-bootstrap = false
swarm-rtbs = 20 # Routing table bucket size
swarm-rtalpha = 3 # Routing table alpha
swarm-randcon = 2 # Number of random connections

# API Config
grpc-server = false
json-server = false
grpc-port = 9091
json-port = 9090
