# sample spacemesh config file
# use the config flag to start a node with a config file.
# e.g $./go-spacemash -config ./config.toml

# Main Config
[main]
data-folder = "~/.spacemesh-data"

# Node Config
[p2p]
security-param = 20
fast-sync = true
tcp-port = 7512
node-id = ""
dial-timeout = "1m"
conn-keepalive = "48h"
network-id = 1 # 0 - MainNet, 1 - TestNet
response-timeout = "2s"

# Node Swarm Config
[swarm]
swarm-bootstrap = false
swarm-rtbs = 20 # Routing table bucket size
swarm-rtalpha = 3 # Routing table alpha
swarm-randcon = 2 # Number of random connections

# API Config
[api]
grpc-server = false
json-server = false
grpc-port = 9091
json-port = 9090

# Time sync NTP Config
[ntp]
max-allowed-time-drift = "10s"
ntp-queries = 5
default-timeout-latency = "10s"
refresh-ntp-interval = "30m"