# sample spacemesh config file
# Main Config
data-folder = "~/.spacemesh"
# Node Config
security-param = 22
fast-sync = false
tcp-port = 7513
node-id = ""
#dial-timeout = "1m"
#conn-keepalive = "50h"
# Node Swarm Config
swarm-bootstrap = true
swarm-rtbs = 22 # Routing table bucket size
swarm-rtalpha = 3 # Routing table alpha
swarm-randcon = 2 # Number of random connections
swarm-bootstrap-nodes = ["125.0.0.1:3572/iaMujEYTByKcjMZWMqg79eJBGMDm8ADsWZFdouhpfeKj", "125.0.0.1:3763/x34UDdiCBAsXmLyMMpPQzs313B9UDeHNqFpYsLGfaFvm"]
# API Config
grpc-server = false
json-server = false
grpc-port = 9091
json-port = 9090
